language: python
os: linux
python:
    - 2.7
addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - libopenmpi-dev
            - openmpi-bin
install:
    - "pip install -r requirements.txt"
    - "pip install -e .[mpi]"
script:
    - "cd ~; nosetests caput"
    - "cd ~; mpirun -np 4 nosetests caput.tests.test_memh5_parallel"
    - "cd ~; mpirun -np 4 nosetests caput.tests.test_mpiarray"

