language: python
os: linux
python:
    - 2.7
addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - libopenmpi-dev
            - openmpi-bin
install:
    - "pip install -r requirements.txt"
    - "python setup.py install"
script: "cd ~; nosetests caput"

